kind: pipeline
type: kubernetes
name: default

metadata:
  namespace: drone

environment:
  CLIENT_ID: 123456789
  CLIENT_SECRET: test-secret
  IS_DEV: true
  DATABASE_URL: 'mongodb://user:pass@mongo:27017/ciam-test?authSource=ciam-test&authMechanism=SCRAM-SHA-256'

steps:
  - name: test
    image: node:17
    commands:
      - npm install --include=dev
      - npm install typescript -g
      - tsc
      - sleep 5
      - npm test

  - name: mongo-version
    image: mongo:5.0.6
    commands:
      - mongo mongo:27017 --eval "db.version()"

services:
  - name: mongo
    image: mongo:5.0.6
    command: [--smallfiles]
    ports:
      - 27017
