kind: pipeline
type: kubernetes
name: default

metadata:
  namespace: drone

environment:
  CLIENT_ID: 123456789
  CLIENT_SECRET: test-secret
  IS_DEV: true
  DATABASE_URL: 'mongodb://mongo:27017/ciam-test'

services:
  - name: mongo
    image: mongo:5

steps:
  - name: mongo-version
    image: mongo:5
    commands:
      - while ! mongo --eval 'db.runCommand("ping").ok' --host mongo --quiet; do sleep 1; done
      - mongo --host mongo:27017 --eval "db.version()"

  - name: test
    image: node:17
    commands:
      - npm install --include=dev
      - npm install typescript -g
      - tsc
      - npm test

  - name: build
    image: plugins/docker
    settings:
      repo: volcanoinc/ciam-backend
      tags: latest
      username:
        from_secret: DOCKER_HUB_USERNAME
      password:
        from_secret: DOCKER_HUB_TOKEN
