kind: pipeline
type: kubernetes
name: default

metadata:
  namespace: drone

steps:
  - name: test
    image: node:17
    commands:
      - npm install --dev
      - npm install typescript -g
      - tsc
      - npm test
