kind: pipeline
type: kubernetes
name: default

metadata:
  namespace: drone

environment:
  CLIENT_ID: 123456789
  CLIENT_SECRET: test-secret
  IS_DEV: true
  DATABASE_URL: 'mongodb://user:pass@mongo:27017/ciam-test?authSource=ciam-test&authMechanism=SCRAM-SHA-256'

steps:
  - name: ping
    image: mongo:4
    commands:
      - sleep 5
      - mongo --eval "db.version()"

services:
  - name: mongo
    image: mongo:4
    command: [--smallfiles]
