kind: pipeline
type: kubernetes
name: default

metadata:
  namespace: drone

environment:
  CLIENT_ID: 123456789
  CLIENT_SECRET: test-secret
  IS_DEV: true
  DATABASE_URL: 'mongodb://user:pass@localhost:27017/ciam-test?authSource=ciam-test&authMechanism=SCRAM-SHA-256'

steps:
  - name: test
    image: node:17
    commands:
      - npm install --dev
      - npm install typescript -g
      - tsc
      - npm test
