openapi: '3.0.2'
info:
  title: Collective IAM
  version: '1.0.0'
servers:
  - url: https://ciam.centralmind.net

paths:
  /role/{roleId}:
    get:
      summary: 'Get a role'
      description: 'Get a role by its roleId'
      security:
        - bearerAuth: ['ciam.role.get.{ROLE_ID}']
      tags:
        - role
    delete:
      security:
        - bearerAuth: ['ciam.role.delete.{ROLE_ID}']
      summary: 'Delete a role'
      description: 'Delete a role by its role ID'
      tags:
        - role
  /role/create:
    post:
      summary: 'Create a role'
      security:
        - bearerAuth: ['ciam.role.create', 'ciam.permission.grant.{FLAGS}']
      description: |
        Create a new role from a name, description, and optionally also its permission flags.<br>
        `ciam.permission.grant.FLAGS` is only checked if permissions are provided, for example if you try to
        create a role with the permissions [`chipware.ban`, `chipware.unban`] then you will need to have the
        permissions [`ciam.permission.grant.chipware.ban`, `ciam.permission.grant.chipware.unban`].
      tags:
        - role
  /role/update:
    post:
      summary: 'Update a role'
      security:
        - bearerAuth:
            [
              'ciam.role.update.{ROLE_ID}',
              'ciam.permission.grant.{FLAGS}',
              'ciam.permission.revoke.{FLAGS}'
            ]
      tags:
        - role
  /role/list:
    get:
      summary: 'List roles'
      description: 'Get a list of all roles'
      security:
        - bearerAuth: ['ciam.role.list']
      tags:
        - role
  /user/create:
    post:
      security:
        - bearerAuth: ['ciam.user.create', 'ciam.permission.grant.{FLAGS}']
      summary: 'Create a user'
      description: |
        Create a new role from at least a name.<br>
        `ciam.permission.grant.FLAGS` is only checked if permissions are provided, for example if you try to
        create a role with the permissions [`chipware.ban`, `chipware.unban`] then you will need to have the
        permissions [`ciam.permission.grant.chipware.ban`, `ciam.permission.grant.chipware.unban`].
      tags:
        - user
  /user/list:
    get:
      summary: 'List users'
      description: 'Get a list of all users'
      security:
        - bearerAuth: ['ciam.user.list']
      tags:
        - user
  /user/{userId}:
    get:
      summary: 'Get a user'
      description: 'Get a user by their user id'
      security:
        - bearerAuth: ['ciam.user.get.{USER_ID}']
      tags:
        - user
    delete:
      summary: 'Delete a user'
      description: 'Delete a user by their user id'
      security:
        - bearerAuth: ['ciam.user.delete.{USER_ID}']
      tags:
        - user
  /user/update:
    post:
      summary: 'Update a user'
      security:
        - bearerAuth:
            [
              'ciam.user.update.{USER_ID}',
              'ciam.permission.grant.{FLAGS}',
              'ciam.permission.revoke.{FLAGS}'
            ]
      tags:
        - user
  /user/me:
    get:
      summary: 'Get own user'
      description: 'Get your own user data, can be useful for validating that the token is valid since this endpoint requires no further permissions.'
      tags:
        - user
  /permission/{flag}:
    get:
      security:
        - bearerAuth: ['ciam.permission.get.{FLAG}']
      summary: 'Get a permission'
      description: 'Get a permission flag'
      tags:
        - permission
    delete:
      security:
        - bearerAuth: ['ciam.permission.delete.{FLAG}']
      summary: 'Delete a permission'
      description: 'Delete a permission flag'
      tags:
        - permission
  /permission/create:
    post:
      security:
        - bearerAuth: ['ciam.permission.create.{FLAG}']
      summary: 'Create a permission'
      tags:
        - permission
  /permission/me:
    get:
      security:
        - bearerAuth: ['ciam.permission.me']
      summary: 'Own permissions'
      description: 'Get your own permissions. Limit and page query parameters lets you easily paginate.'
      tags:
        - permission
  /permission/list:
    get:
      security:
        - bearerAuth: ['ciam.permission.list.{SEARCH}']
      summary: 'List permissions'
      description: 'Lets you list permissions. Limit and page query parameters lets you easily paginate.'
      tags:
        - permission
  /permission/update:
    post:
      security:
        - bearerAuth: ['ciam.permission.update.{FLAG}']
      summary: 'Update a permission'
      tags:
        - permission
  /permission/upsert:
    post:
      security:
        - bearerAuth: ['ciam.permission.upsert.{FLAG}']
      summary: 'Upsert a permission'
      description: |
        Upserting tries to update a permission if it already exists, or create a new one if none was found
        with the given flag.
      tags:
        - permission
  /permission/has:
    post:
      security:
        - bearerAuth: ['ciam.permission.has.{ALL_REQUIRED_PERMISSIONS}']
      summary: 'Check permissions'
      description: 'Check if a user or role has the provided permissions.'
      tags:
        - permission
  /login/identify:
    get:
      summary: 'Simple OAuth endpoint'
      description: |
        Redirect users to this endpoint to perform a simple version of OAuth.
        Once the flow is complete the user will be redirected to your website with a code. You can then use this code to get the user info.
      tags:
        - auth
  /auth/identify/{code}:
    get:
      summary: 'Get user information'
      description: |
        Get user information from a code after they have completed the indentification flow.
      tags:
        - auth
  /login:
    get:
      summary: 'Redirect endpoint for OAuth'
      description: |
        Once the user has completed the Oauth2 flow they will be redirected to the `returnUrl`, they will have a cookie
        set for the domain `domain`, this cookie can be used to access the users information.
      tags:
        - auth
  /auth/user:
    get:
      summary: 'Get user'
      description: |
        Get a user from the access token.
      tags:
        - auth
  /auth/refresh:
    get:
      summary: 'Refresh access token'
      description: |
        Refresh an access token for a user.
      tags:
        - auth
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT